Correction to linspace call in hough_line default
scikit-image/scikit-image pull request #5182
Opened 2021-01-11 07:05 UTC by madphysicist

## Description

`theta = np.pi / 2 - np.arange(180) / 180.0 * np.pi` done correctly below in the probabilistic transform.

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

2021-01-11 15:16 UTC, pep8speaks commented
Hello @madphysicist! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`skimage/transform/hough_transform.py`](https://github.com/scikit-image/scikit-image/blob/086683f8cce84e3a673f75a2db7a2ba536d4b499/skimage/transform/hough_transform.py):

> [Line 177:80](https://github.com/scikit-image/scikit-image/blob/086683f8cce84e3a673f75a2db7a2ba536d4b499/skimage/transform/hough_transform.py#L177): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 244:80](https://github.com/scikit-image/scikit-image/blob/086683f8cce84e3a673f75a2db7a2ba536d4b499/skimage/transform/hough_transform.py#L244): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

2021-01-12 15:36 UTC, madphysicist commented
Should I squash the commits?

2021-01-13 09:05 UTC, sciunto requested changes
Thanks for the PR! No need to squash, we will do it. Perhaps, to improve the example, it would be better to have two lines at different absolute angles like 45° and -30°. What do you think?

2021-01-13 12:35 UTC, madphysicist commented
@sciunto I'm not sure that I understand what example you're referring to? My goal was to fix some small imprecisions that I noticed rather than to add anything fundamentally new. I'd be happy to add something if you like though.

2021-01-13 16:09 UTC, sciunto commented
> @sciunto I'm not sure that I understand what example you're referring to? 

The one you changed: https://scikit-image.org/docs/stable/auto_examples/edges/plot_line_hough_transform.html#sphx-glr-auto-examples-edges-plot-line-hough-transform-py

2021-01-13 18:58 UTC, madphysicist commented
@sciunto. I made the example look like this:

![image](https://user-images.githubusercontent.com/4617010/104496759-02332780-559f-11eb-875a-901ef6991267.png)

Three lines, but I think it's in keeping with what you requested.

2021-01-13 20:35 UTC, madphysicist commented
Looks like the build errors are caused by a timeout rather than an actual error

2021-01-14 00:57 UTC, madphysicist commented
If we can agree on this PR, please merge before #5183.

2021-01-14 09:21 UTC, sciunto requested changes

2021-01-14 09:21 UTC, sciunto commented on doc/examples/color_exposure/plot_tinting_grayscale_images.py
> +                            1 + 0.5 / len(hue_gradient), 0, 0.2))
This change seems unrelated to this PR. Please revert.

2021-01-14 09:21 UTC, sciunto commented on doc/examples/numpy_operations/plot_view_as_blocks.py
> +ax[0].imshow(l_resized, extent=(-0.5, 128.5, 128.5, -0.5),
This change seems unrelated to this PR. Please revert.

2021-01-14 09:21 UTC, sciunto commented on doc/examples/transform/plot_radon_transform.py
> +           aspect='auto')
This change seems unrelated to this PR. Please revert.

2021-01-14 09:21 UTC, sciunto commented on skimage/viewer/plugins/color_histogram.py
> +        ab_extents = [left - 0.5, right + 0.5, right + 0.5, left - 0.5]
This change seems unrelated to this PR. Please revert. (And this module is deprecated, will be removed soon, so no need to maintain this code).

2021-01-15 01:30 UTC, madphysicist commented
@sciunto I've moved the updates to #5184. The changes were keeping in the spirit of what I am trying to do here, but I can see that they are easier to process in a separate PR.

2021-01-15 07:39 UTC, jni approved these changes
:+1: nice!

2021-01-15 07:46 UTC, sciunto approved these changes
perfect!

2021-01-15 07:46 UTC, merged

2021-01-15 07:46 UTC, sciunto commented
thank you

2021-01-15 09:06 UTC, stefanv commented
@madphysicist @sciunto Does this mean we're finally ready for https://github.com/scikit-image/scikit-image/pull/4877 ? :)

2021-01-15 11:18 UTC, madphysicist commented
@stefanv This is not totally related, but sure.