Update RELEASE.txt
scikit-image/scikit-image pull request #5431
Opened 2021-06-18 11:47 UTC by leej3

Resolves #5423

This is the release workflow as I know understand it to be.

Feedback on the implementation itself also welcome (now that it is more
explicitly documented).

## Description

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

2021-06-18 15:48 UTC, mkcor commented on RELEASE.txt
> +    git push upstream buildwheel_0.19.0test
Shouldn't this be something like
```suggestion
    git push upstream buildwheel_<major>.<minor>.0test
```
?

2021-06-18 16:03 UTC, leej3 commented on RELEASE.txt
> +    git push upstream buildwheel_0.19.0test
yes that's better. thanks

2021-06-20 14:11 UTC, grlee77 requested changes
I requested one small change, but this otherwise looks good to me

2021-06-20 14:11 UTC, grlee77 commented on RELEASE.txt
> +    git tag -m <github_release_message> buildwheel_0.19.0test
```suggestion
    git tag -m <github_release_message> buildwheel_<major>.<minor>.0test
```

use major/minor as in step 2 below

2021-06-25 20:55 UTC, grlee77 approved these changes

2021-06-25 20:58 UTC, merged