fix phase_cross_correlation for 3D with reference masks
scikit-image/scikit-image pull request #5559
Opened 2021-09-07 13:57 UTC by sommerc

## Description

fixes issue [4980](https://github.com/scikit-image/scikit-image/issues/4980) (and potentially [5458](https://github.com/scikit-image/scikit-image/issues/5458))

cross_correlation axes were hard-coded for 2D

## Checklist

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

2021-09-07 13:57 UTC, pep8speaks commented
Hello @sommerc! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`skimage/registration/_masked_phase_cross_correlation.py`](https://github.com/scikit-image/scikit-image/blob/a3551dd0db335f6f3f49f9bd10395dc316e04391/skimage/registration/_masked_phase_cross_correlation.py):

> [Line 80:80](https://github.com/scikit-image/scikit-image/blob/a3551dd0db335f6f3f49f9bd10395dc316e04391/skimage/registration/_masked_phase_cross_correlation.py#L80): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (101 > 79 characters)

2021-09-07 14:11 UTC, grlee77 requested changes
Wow, thanks for finding this! 

Can you please also add a 3D test case (perhaps using `skimage.data.binary_blobs`) similar to the first or second test that is currently in `skimage/registration/tests/test_masked_phase_cross_correlation.py`? It looks like the 3D tests that we have now only check some basic properties, but do not verify 3D displacement estimates.

2021-09-08 08:59 UTC, sommerc commented
Hi @grlee77, 

I wrote a little 3D test with masks using `skimage.data.brain`, which direclty compares an applied 3d-shift with the meassured shift. Sorry for the white-space commit mess...

Cheers,
Chris

2021-09-08 12:51 UTC, grlee77 approved these changes
Thanks @sommerc. This looks good to me.

We could possibly use `brain[:, ::2, ::2]` to get a smaller image so the test would complete in < 1 second, but is not too long as is (~2-3 seconds on my system).

Don't worry about extra white space commits. We will squash the commits on merge anyway and can clean up the commit message history at that time.

2021-09-10 16:59 UTC, merged

2021-09-10 16:59 UTC, grlee77 commented
Merged, thanks again @sommerc!