Default footprint for the median filter
scikit-image/scikit-image pull request #5594
Opened 2021-10-04 19:10 UTC by haesleinhuepf

## Description

This addresses #5593 and demonstrates how a default-footprint for the `median` filter could look like.

## Checklist

- [x] [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [ ] Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- [x] Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- [x] Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
      `doc/release/release_dev.rst`.

2021-10-04 19:10 UTC, pep8speaks commented
Hello @haesleinhuepf! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`skimage/filters/tests/test_median.py`](https://github.com/scikit-image/scikit-image/blob/36667cb593d593490251349ee9d5c8bc0bbd55c7/skimage/filters/tests/test_median.py):

> [Line 19:1](https://github.com/scikit-image/scikit-image/blob/36667cb593d593490251349ee9d5c8bc0bbd55c7/skimage/filters/tests/test_median.py#L19): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 88:1](https://github.com/scikit-image/scikit-image/blob/36667cb593d593490251349ee9d5c8bc0bbd55c7/skimage/filters/tests/test_median.py#L88): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 94:1](https://github.com/scikit-image/scikit-image/blob/36667cb593d593490251349ee9d5c8bc0bbd55c7/skimage/filters/tests/test_median.py#L94): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2021-10-05 09:20 UTC, rfezzani requested changes
Thank you @haesleinhuepf. This looks like a good addition, but we need to manage `image.ndim > 3`. I see 3 options, when `footprint` is an `int` and `image.ndim > 3`
- raise an error,
- set back `footprint` to `None` with a warning,
- add `ball` support for nD.

2021-10-05 09:20 UTC, rfezzani commented on skimage/filters/_median.py
> +    if footprint is not None and isinstance(footprint, int):
Since
```python
>>> isinstance(None, int)
False
```
This is equivalent to
```suggestion
    if isinstance(footprint, int):
```

2021-11-03 13:19 UTC, grlee77 commented
> Ok, cool. I'm fine with that. Just one question: What's the difference between scipy.ndimage.median_filter and skimage.filters.median? Is the latter just kept for backwards compatibility? Updating it might then be not necessary ;-)

The main difference is that `skimage.filters.median` has a `behavior` kwarg that selects a different implementation than the SciPy one if `behavior='rank'` (in that cases it uses `skimage.filters.rank.median`). That implementation [supports an image mask](https://scikit-image.org/docs/stable/api/skimage.filters.rank.html#skimage.filters.rank.median), for instance, but is only for 2D or 3D data of certain integer types.

2021-11-03 18:37 UTC, haesleinhuepf commented
Hi @grlee77, ok cool. Thanks for the answer. I will close this PR for now. I think I would replicate things in SciPy, which might not be necessary. Thanks again for the feedback and the support! ;-)

2021-11-03 18:37 UTC, closed without merging