New thumbnails for General-purpose images and scientific images
scikit-image/scikit-image pull request #6298
Opened 2022-03-22 14:57 UTC by kolibril13

## Description

Fixes https://github.com/scikit-image/scikit-image/issues/4384#
This PR adds a nice thumbnail for the General-purpose images:
<img width="162" alt="image" src="https://user-images.githubusercontent.com/44469195/159510268-e286e390-b7fb-4a61-bc93-f199bc315b59.png">

I used the variable `sphinx_gallery_thumbnail_number = -1` (see https://sphinx-gallery.github.io/stable/auto_examples/plot_4_choose_thumbnail.html) , so  sphinx will recognize the right image for the thumblail. 
I am converting it from draft to real PR as soon as the docs build looks good.
@grlee77: Could you review this pr?
## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

2022-03-22 14:57 UTC, pep8speaks commented
Hello @kolibril13! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`doc/examples/data/plot_general.py`](https://github.com/scikit-image/scikit-image/blob/8ae3eda6faeee2fbf3e946c3e00ec2de97ff8012/doc/examples/data/plot_general.py):

> [Line 54:1](https://github.com/scikit-image/scikit-image/blob/8ae3eda6faeee2fbf3e946c3e00ec2de97ff8012/doc/examples/data/plot_general.py#L54): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 55:1](https://github.com/scikit-image/scikit-image/blob/8ae3eda6faeee2fbf3e946c3e00ec2de97ff8012/doc/examples/data/plot_general.py#L55): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 56:1](https://github.com/scikit-image/scikit-image/blob/8ae3eda6faeee2fbf3e946c3e00ec2de97ff8012/doc/examples/data/plot_general.py#L56): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 58:39](https://github.com/scikit-image/scikit-image/blob/8ae3eda6faeee2fbf3e946c3e00ec2de97ff8012/doc/examples/data/plot_general.py#L58): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2022-03-22 15:38 UTC, grlee77 requested changes
The suggestions here are the ones the pep8 bot was warning about. Otherwise this looks good (pending final rendered doc check)

2022-03-22 15:38 UTC, grlee77 commented on doc/examples/data/plot_general.py
> +from skimage import data
Can you move the numpy import after the matplotlib ones above (the other two here are duplicate imports)

```suggestion
```

2022-03-22 15:38 UTC, grlee77 commented on doc/examples/data/plot_general.py
> +# sphinx_gallery_thumbnail_number = -1
```suggestion
# sphinx_gallery_thumbnail_number = -1
```

2022-03-22 15:51 UTC, grlee77 commented
Not sure if there is good way to not also have the thumbnail appear in the gallery itself? It looks like the other option is to [store a static image and then point to that for the thumbnail](https://sphinx-gallery.github.io/stable/auto_examples/plot_4b_provide_thumbnail.html#providing-a-figure-for-the-thumbnail-image). That is problematic if our datasets change, though (rare, but has happened a couple of times in the past).

2022-03-22 16:55 UTC, kolibril13 commented
I don't like too much to add static images to git as it will increase the repo size and I think it's nice to have this auto-updating option. Manually re-creating the thumbnail everytime the data changes feels like extra work, which would also have to be kept in mind. By auto-generating the thumbnail, less manual work would be required, and a good side effect is that there is a new example of how to create a grid with three dots that indicate further images.
The doc artifact preview looks nice:
<img width="294" alt="image" src="https://user-images.githubusercontent.com/44469195/159533066-eea9a7f4-e54c-4a89-a903-c20707a6b883.png">
However, the example looks a bit odd, as it is one big example:
https://3680-2014929-gh.circle-artifacts.com/0/doc/build/html/auto_examples/data/plot_general.html#sphx-glr-auto-examples-data-plot-general-py
I ll try to split it into two examples, similar to here: https://scikit-image.org/docs/stable/auto_examples/registration/plot_stitching.html?highlight=stitching
I guess, I just have to add this syntax:
```py
############################################################################
# Thumbnail image for the gallery
```

2022-03-22 17:03 UTC, kolibril13 commented
Do I have to do something to trigger the Github Actions? It seems they were not triggered by the last commit
<img width="600" alt="image" src="https://user-images.githubusercontent.com/44469195/159535018-e019b2bb-85f3-4ca1-9879-abece838fc80.png">

2022-03-22 19:10 UTC, kolibril13 commented
Here is the latest version: https://3683-2014929-gh.circle-artifacts.com/0/doc/build/html/auto_examples/index.html
I think this is now ready for review.
Two more advantages of keeping the code for the thumbail examples in the docs:

* It becomes clear that images can be accessed in this object oriented way
* The functions are clickable and directly linked to the place where more information about the images is provided
<img width="435" alt="image" src="https://user-images.githubusercontent.com/44469195/159556852-9414d4e9-e83e-4d1d-93ad-3b46b277bb36.png">

2022-03-23 00:15 UTC, grlee77 commented
> https://3683-2014929-gh.circle-artifacts.com/0/doc/build/html/auto_examples/index.html

Yeah, this looks better. There is much clearer separation from the individual example images now.

I do think the 3 x 3 grid looks pretty nice as well. I also liked your suggestion to do the same thing for the scientific images as well. It may be easiest to just also add that here, but also fine if you want to do it in a separate PR.

2022-03-23 00:18 UTC, grlee77 approved these changes
I have approved the PR, but will leave open for a bit to see if there is any other feedback. If you want to play with switching to 3x3 or updating the scientific images as well, please go ahead

2022-03-23 06:56 UTC, kolibril13 commented
I've changed to the 3x3 example now.
And I will do the scientific images images thumbnail in a seperate pr after this one is merged.

2022-03-23 21:52 UTC, kolibril13 commented
Seems like Github has a lot of problems today, error this time: "Artifact not found"  I will run the CI again.

2022-03-24 08:32 UTC, jni approved these changes

2022-03-24 09:36 UTC, kolibril13 commented
Latest version:
https://output.circle-artifacts.com/output/job/9bb49f1a-8b71-4f48-832f-884648e5d3f2/artifacts/0/doc/build/html/auto_examples/index.html
<img width="541" alt="image" src="https://user-images.githubusercontent.com/44469195/159886500-79f9db9d-2d46-4371-824a-f77e6a63caa7.png">
I will increase the spacing for the scientific images a bit

2022-03-24 10:21 UTC, kolibril13 commented
https://output.circle-artifacts.com/output/job/463790b2-ec5e-4f72-a0af-53327f6f4e53/artifacts/0/doc/build/html/auto_examples/index.html
I think now it looks great!
<img width="531" alt="image" src="https://user-images.githubusercontent.com/44469195/159895087-b531204d-55b2-4ea2-b12f-1ec83ee7dfac.png">
But the specific images could also be tweaked, what about this new thumbnail?
<img width="312" alt="image" src="https://user-images.githubusercontent.com/44469195/159895287-a22a3fb5-cbd9-4aeb-a914-a6c07fc51ae6.png">
(last one is generated with)
```py

from matplotlib.offsetbox import AnchoredText

ax1 = plt.subplot(2,2,1)
ax1.imshow(left_motorcycle)
ax1.add_artist(AnchoredText("Stereo", prop=dict(size=20), frameon=True , borderpad=0, loc='upper left'))
ax2 = plt.subplot(2,2,2)
ax2.imshow(left_vortex)
ax2.add_artist(AnchoredText("PIV", prop=dict(size=20), frameon=True , borderpad=0, loc='upper left'))

ax3 = plt.subplot(2,4,5)
ax3.imshow(im1, cmap="gray")
ax4 = plt.subplot(2,4,6)
ax4.imshow(im2, cmap="gray")
ax5 = plt.subplot(2,4,7)
ax5.imshow(im3, cmap="gray")
ax6 = plt.subplot(2,4,8)
ax6.imshow(im4, cmap="gray")
for ax in [ax1,ax2,ax3,ax4,ax5,ax6]:
    ax.axis("off")
plt.tight_layout()
```

2022-03-24 19:14 UTC, grlee77 approved these changes
LGTM!

2022-03-29 16:35 UTC, lagru reviewed
Added some style changes / suggestions so that the PEP8 bot is satisfied.

2022-03-29 16:35 UTC, lagru commented on doc/examples/data/plot_general.py
> +import numpy as np
```suggestion
import numpy as np

```

2022-03-29 16:35 UTC, lagru commented on doc/examples/data/plot_scientific.py
> +
```suggestion
```

2022-03-29 16:35 UTC, lagru commented on doc/examples/data/plot_general.py
> +plt.subplots_adjust(wspace=0.1, hspace=0.1)
```suggestion
plt.subplots_adjust(wspace=0.1, hspace=0.1)

```

2022-03-29 16:39 UTC, merged

2022-03-29 16:48 UTC, lagru commented
Just saw that you already opened #6301 :smile: