adapted rand error with alpha
scikit-image/scikit-image pull request #6472
Opened 2022-08-18 14:15 UTC by lucas-johnson

Resolves https://github.com/scikit-image/scikit-image/issues/6433

2022-08-18 14:15 UTC, pep8speaks commented
Hello @lucas-johnson! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`skimage/metrics/_adapted_rand_error.py`](https://github.com/scikit-image/scikit-image/blob/95683aad7bf1bd4b54ba0c9c40ddc7d427d7329f/skimage/metrics/_adapted_rand_error.py):

> [Line 34:80](https://github.com/scikit-image/scikit-image/blob/95683aad7bf1bd4b54ba0c9c40ddc7d427d7329f/skimage/metrics/_adapted_rand_error.py#L34): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 79 characters)
> [Line 35:80](https://github.com/scikit-image/scikit-image/blob/95683aad7bf1bd4b54ba0c9c40ddc7d427d7329f/skimage/metrics/_adapted_rand_error.py#L35): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 79 characters)
> [Line 36:80](https://github.com/scikit-image/scikit-image/blob/95683aad7bf1bd4b54ba0c9c40ddc7d427d7329f/skimage/metrics/_adapted_rand_error.py#L36): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 37:80](https://github.com/scikit-image/scikit-image/blob/95683aad7bf1bd4b54ba0c9c40ddc7d427d7329f/skimage/metrics/_adapted_rand_error.py#L37): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)

2022-08-19 17:12 UTC, alexdesiqueira requested changes
Thank you @lucas-johnson!
I'll ask a few changes on the documentation, but otherwise this one looks good to me.

2022-08-19 17:12 UTC, alexdesiqueira commented on skimage/metrics/_adapted_rand_error.py
> +        in the test image.
```suggestion
The adapted Rand error.
```

The remainder should be in `Notes`.

2022-08-19 17:43 UTC, lucas-johnson commented
Documentation tweaks made!

2022-08-19 18:51 UTC, lucas-johnson commented
As near as I can tell that test failure looks unrelated to this PR... local pytests are passing, with the exception of benchmark tests.

2022-08-24 18:44 UTC, alexdesiqueira approved these changes

2022-08-24 18:45 UTC, alexdesiqueira commented
Thank you @lucas-johnson! Looks good, thanks for this!

2022-08-24 18:46 UTC, alexdesiqueira commented
On the CI tests, I opened an issue: #6479.

2022-08-29 19:02 UTC, alexdesiqueira commented
@scikit-image/core please check and merge (if OK) / discuss (if not) this one. Thanks y'all!

2022-08-30 09:10 UTC, rfezzani approved these changes
Thank you @lucas-johnson for your contribution, I just found a minor formatting issue :wink:

2022-08-30 09:10 UTC, rfezzani commented on skimage/metrics/_adapted_rand_error.py
> +       calculation.
```suggestion
        Relative weight given to precision and recall in the adapted Rand error
        calculation.
```
just aligning the tabulation ;)

2022-08-30 10:01 UTC, jni approved these changes

2022-08-31 08:50 UTC, merged

2022-08-31 08:51 UTC, rfezzani commented
Pushing the green button :tada:  :slightly_smiling_face: Thank you @lucas-johnson