Start deprecation of inconsistency in phase_cross_correlation output count
scikit-image/scikit-image pull request #6543
Opened 2022-09-26 11:26 UTC by lagru

## Description

Closes #4764.

Depending on return_error and if masked cross-correlation is used, the function returns either shifts or a tuple of shifts, error and phasediff. This API inconsistency shall be deprecated in favor of always returning shifts, error and phasediff.

Deprecation plan:
- This release (0.20?): raise a warning that next release will start returning error and phasediff (as NaN if mask is supplied). The warning goes away with return_error="always", which also changes to the new behavior of always returning error and phasediff.
- Next release (0.21 or 2.0?): deprecate return_error, and make returning 3 outputs the default.

We warn only were a single output is returned as opposed to doing a general warning for return_error != "always". This saves users who are already using the function with 3 outputs from having to update their use of the function.

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

2022-10-17 12:18 UTC, grlee77 requested changes
Thanks, @lagru. This looks good aside from one suggested indentation fix.

2022-10-17 12:18 UTC, grlee77 commented on skimage/registration/_phase_cross_correlation.py
> +         is "always".
```suggestion
        ``reference_image`` and ``moving_image``. For masked cross-correlation
        this error is not available and NaN is returned if ``return_error``
        is "always".
```

2022-12-02 20:41 UTC, stefanv approved these changes

2022-12-02 20:52 UTC, grlee77 approved these changes

2022-12-02 21:15 UTC, merged