Add linting via pre-commit
scikit-image/scikit-image pull request #6563
Opened 2022-10-05 22:15 UTC by stefanv

Add some standard formatting checks via pre-commit.

Eventually, it would be nice to add black or something similar here, but that'd need to be discussed first.

2022-10-05 22:16 UTC, stefanv commented
/cc @jarrodmillman for review

2022-10-06 02:10 UTC, jarrodmillman requested changes
LGTM. You can autolint in a separate PR, so that the commit hash can be added to `.git-blame-ignore-revs`.

2022-10-06 02:10 UTC, jarrodmillman commented on .pre-commit-config.yaml
> +    rev: v2.38.2
```suggestion
    rev: v3.0.0
```

2022-10-06 02:10 UTC, jarrodmillman commented on .pre-commit-config.yaml
> +    rev: 3.8.4
```suggestion
    rev: 5.0.4
```

2022-10-06 06:21 UTC, stefanv commented
@jarrodmillman Do you think it's best to change files gradually as they get touched, or to do this as a one-off sweep as you suggest above?

2022-10-09 02:26 UTC, jarrodmillman commented
I would do it once. I've done it in several projects and didn't run into any issues. Why not try it and if it causes issues just revert the change (or even git reset to the previous commit and git push to main)?

2022-10-09 10:20 UTC, lagru reviewed
Thanks for getting this started @stefanv. I'm not clear on how this will impact our workflow as I don't have much experience with this yet. Will we be able to override these hooks in case they prove to restrictive or have a bug?

2022-10-09 10:20 UTC, lagru commented on .pre-commit-config.yaml
> +  - repo: https://gitlab.com/pycqa/flake8
Wondering why you use the GitLab mirror here?

2022-10-09 10:20 UTC, lagru commented on .pre-commit-config.yaml
> +    rev: v4.3.0
I think when using hooks from third parties, the same logic as for the GitHub actions applies and pinning to a specific commit is good practice. If you agree I'll do the work and suggest these changes. ;)

2022-10-09 21:41 UTC, stefanv commented
Go ahead and make the fixes you suggest, @lagru, they look fine to me.

The pre-commit is run in CI to ensure that everything conforms to the standards we define. Rewriting the code isn't necessary, but it also doesn't matter, so not sure it's worth figuring out how to switch it off.

2022-10-11 12:08 UTC, lagru commented
Hmm, currently [pre-commit/action](https://github.com/pre-commit/action) is run on every file in our repo, which would preclude us from migrating step by step. There is https://github.com/pre-commit/action/issues/7 but that introduces another action dependency. 

I don't like the idea of asking a contributor to address all linting changes, e.g as found by flake8, in a long file himself even though only a small bit was changed. So I'd also advocate doing it once, though that PR might be a large barrier.

2022-10-11 13:48 UTC, jarrodmillman commented
See #6568.

2022-10-11 18:18 UTC, stefanv commented
We'll make a single commit with all linting changes, and add it to the `.git-blame-ignore-revs` to keep git blame history clean.

2022-10-12 01:01 UTC, jarrodmillman approved these changes

2022-10-12 01:10 UTC, stefanv commented
I'm going to merge this to ensure that we don't get any other PRs merged on top of the linting patch.

2022-10-12 01:10 UTC, merged

2022-10-12 01:41 UTC, jarrodmillman commented on .github/workflows/lint.yml
> +      - uses: pre-commit/action@v3.0.0
Let's deal with it later.