Resolved the misleading error message on passing an invalid method
scikit-image/scikit-image pull request #6805
Opened 2023-03-09 17:31 UTC by rum1887

Added an elif condition to check for the validity of the method passed.
Resolves issue #6661

## Description

## Checklist

- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- Gallery example in `./doc/examples` (new features only)
- Benchmark in `./benchmarks`, if your changes aren't covered by an
  existing benchmark
- Unit tests
- Clean style in [the spirit of PEP8](https://www.python.org/dev/peps/pep-0008/)
- Descriptive commit messages (see below)

## For reviewers

- Check that the PR title is short, concise, and will make sense 1 year
  later.
- Check that new functions are imported in corresponding `__init__.py`.
- Check that new features, API changes, and deprecations are mentioned in
  `doc/release/release_dev.rst`.
- There is a bot to help automate backporting a PR to an older branch. For
  example, to backport to v0.19.x after merging, add the following in a PR
  comment: `@meeseeksdev backport to v0.19.x`
- To run benchmarks on a PR, add the `run-benchmark` label. To rerun, the label
  can be removed and then added again. The benchmark output can be checked in
  the "Actions" tab.

2023-03-10 13:26 UTC, jni requested changes
Hi @rum1887, I've made a suggestion to comply with [PEP8 formatting](https://pep8.org), and also tweak the wording a little.

Also, could you add a test for this? You can see an example of how to do this here:

https://github.com/scikit-image/scikit-image/blob/d2f8e47311eacc5aa94186f5cd1f077316df004e/skimage/morphology/tests/test_skeletonize.py#L25-L28

You should be able to copy those lines and adapt them to test this error message is raised.

2023-03-10 17:15 UTC, rum1887 commented
> Hi @rum1887, I've made a suggestion to comply with [PEP8 formatting](https://pep8.org), and also tweak the wording a little.
> 
> Also, could you add a test for this? You can see an example of how to do this here:
> 
> https://github.com/scikit-image/scikit-image/blob/d2f8e47311eacc5aa94186f5cd1f077316df004e/skimage/morphology/tests/test_skeletonize.py#L25-L28
> 
> You should be able to copy those lines and adapt them to test this error message is raised.



> Hi @rum1887, I've made a suggestion to comply with [PEP8 formatting](https://pep8.org), and also tweak the wording a little.
> 
> Also, could you add a test for this? You can see an example of how to do this here:
> 
> https://github.com/scikit-image/scikit-image/blob/d2f8e47311eacc5aa94186f5cd1f077316df004e/skimage/morphology/tests/test_skeletonize.py#L25-L28
> 
> You should be able to copy those lines and adapt them to test this error message is raised.

yes, on it!

2023-03-10 21:29 UTC, rum1887 commented
> Hi @rum1887, I've made a suggestion to comply with [PEP8 formatting](https://pep8.org), and also tweak the wording a little.
> 
> Also, could you add a test for this? You can see an example of how to do this here:
> 
> https://github.com/scikit-image/scikit-image/blob/d2f8e47311eacc5aa94186f5cd1f077316df004e/skimage/morphology/tests/test_skeletonize.py#L25-L28
> 
> You should be able to copy those lines and adapt them to test this error message is raised.

Hi @jni , I have added a unit test

2023-03-11 01:26 UTC, jni commented on skimage/morphology/tests/test_skeletonize.py
> +            skeletonize(im,method='foo')
```suggestion
            skeletonize(im, method='foo')
```

2023-03-11 01:26 UTC, jni approved these changes
This is ready imho! Thank you @rum1887! 😊

2023-03-11 08:11 UTC, rum1887 commented
> This is ready imho! Thank you @rum1887! 😊 

Thanks @jni for the review, it was fun working on this and I'm excited to contribute more, do you mind pointing me to more issues?

2023-03-11 14:11 UTC, lagru requested changes
Hey @rum1887, I noticed that another applicant was working on this in #6798 before you. I think they started on this in #6793 which was already closed when you created this one and than continued their work in #6798. 

I am assuming that there was a misunderstanding? In the future, please take care to check if there is any previous work on this, especially by a fellow Outreachy applicant. And if there is, please feel welcome to work together and review each others contributions! There should be enough work for everyone.

@arsh73552, I'm sorry for the situation. It seems like this PR is much farther along. 

@mkcor, @jni how should we handle this situation to be fair for each applicant? Considering that their solutions were quite similar, should we include @arsh73552 as a co-author so that both can record their contribution?

2023-03-11 17:50 UTC, arsh73552 commented
Ahh, I see.. It's ok I'll find other issues to work on.

2023-03-12 07:57 UTC, rum1887 commented
I'm sorry :(

I realize now that I should have reviewed the previous work before working on the issue. The PR was closed, so I took up the issue! 

Will ask before taking up an issue henceforth and if there's previous work on the issue, will review it instead of creating a new pr. 

I don't mind if @arsh73552 PR is merged

2023-03-12 08:13 UTC, jni commented
I like the idea of co-authorship, thank you for suggesting it @lagru — do you mind doing that in the merge commit message? I think you'll need to grab another commit from @arsh73552 to get the right `Co-authored by: author-name <email>` combo.

All good @rum1887, and sorry everyone that I also missed the other PR. It's a busy time with all the Outreachy contributions! 😅 Thanks all! 🙏

2023-03-12 13:28 UTC, arsh73552 commented
Thanks, that sounds great to me! I've created a PR to help with the same.

2023-03-12 14:29 UTC, lagru approved these changes

2023-03-12 14:34 UTC, lagru commented
Thanks everyone for being so understanding! :pray: I don't think anyone wanted to step on anyone's toes and as @jni said, it's a bit busier than usual and it can be hard to keep track of something even during more quiet times. :sweat_smile: 

I'll merge once the CI is green and include @arsh73552 as a co-author. :rocket:

2023-03-13 23:04 UTC, merged

2023-03-13 23:05 UTC, lagru commented
Thanks everyone! @rum1887 and @arsh73552 you are both included in 4968b71e144d06ec459a26ba88980cc4f099d78a as authors. :)