Require imageio>=2.33 to fix incompatibility with Pillow>=10.1.0
scikit-image/scikit-image pull request #7245
Opened 2023-11-20 03:37 UTC by sitic

## Description
Pillow release 10.1.0 broke imageio, the new imageio release 2.33.0 fixes the issue ([upstream fix](https://github.com/imageio/imageio/pull/1045)).

Require imageio>=2.33 and revert the hotfix Pillow pin.

Closes #7207 
Reverts #7208 

## Release note

Summarize the introduced changes in the code block below in one or a few sentences. The
summary will be included in the next release notes automatically:

```release-note
Update imageio to fix Pillow incompatibility
```

2023-11-21 17:14 UTC, stefanv approved these changes

2023-11-21 20:18 UTC, sitic commented
The min requirement tests are failing because the new imageio tries to use `PIL.GifImagePlugin.LOADING_STRATEGY`, which is only available for `pillow>=9.1.0`, but the min requirements tests use `Pillow==9.0.1`.

I've filed an imageio bug report
- https://github.com/imageio/imageio/issues/1052

2023-11-22 21:16 UTC, mkcor commented
Thanks for looking into this, @sitic!

@stefanv do we want to wait for an [upstream fix](https://github.com/imageio/imageio/issues/1052#issuecomment-1822175295) or pin
```
pillow>=9.1.0,<10.1.0
```
in `requirements/default.txt`?

2023-11-22 21:42 UTC, stefanv commented
Do you mean:

```
pillow>=9.1.0
```

? That seems fine.

2023-11-23 10:36 UTC, mkcor commented
> Do you mean:
> 
> ```
> pillow>=9.1.0
> ```
> 
> ? That seems fine.

Oops, yes, sorry! @sitic do you mind updating the PR accordingly?

2023-11-24 16:13 UTC, jarrodmillman requested changes

2023-11-24 16:13 UTC, jarrodmillman commented on pyproject.toml
> +    'pillow>=9.0.1',
```suggestion
    'pillow>=9.1',
```

2023-11-24 16:13 UTC, jarrodmillman commented on requirements/default.txt
> +pillow>=9.0.1
```suggestion
pillow>=9.1
```

2023-11-24 16:25 UTC, mkcor approved these changes
:shipit:

2023-11-24 16:35 UTC, jarrodmillman approved these changes

2023-11-24 16:35 UTC, merged